#!/usr/bin/env python3
"""
Proven Browser Manager for CapCut Automation
Integrates our proven undetected ChromeDriver session with the main automation system.
Uses the proven_session.json file generated by our working login solution.
"""

import os
import sys
import json
import time
from pathlib import Path
from typing import Optional, Dict, Any
from datetime import datetime
from urllib.parse import urlparse
from dotenv import load_dotenv

try:
    import undetected_chromedriver as uc
    from selenium import webdriver
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.support import expected_conditions as EC
    SELENIUM_AVAILABLE = True
except ImportError:
    SELENIUM_AVAILABLE = False

try:
    from playwright.sync_api import sync_playwright, Browser, BrowserContext, Page
    PLAYWRIGHT_AVAILABLE = True
except ImportError:
    PLAYWRIGHT_AVAILABLE = False


class ProvenBrowser:
    """
    Browser manager that uses our proven session JSON file.
    Replaces the complex login logic with simple session loading.
    """
    
    # CapCut URLs (kept for backward compatibility, but not used for routing)
    CAPCUT_LOGIN_URL = "https://www.capcut.com/login"
    CAPCUT_DASHBOARD_URL = "https://www.capcut.com/workspace"
    CAPCUT_CREATE_URL = "https://www.capcut.com/editor"
    CAPCUT_AI_CREATOR_URL = "https://www.capcut.com/ai-video-generator"
    
    def __init__(self, env_file: Optional[str] = None):
        """Initialize ProvenBrowser with proven session support."""
        # Load environment variables
        if env_file:
            load_dotenv(env_file)
        else:
            load_dotenv()
        
        # Project paths (original behavior: state under project root parent)
        self.project_root = Path(__file__).parent.parent
        self.state_dir = self.project_root / "state"
        self.proven_session_file = self.state_dir / "proven_session.json"
        self.state_file = self.state_dir / "state.json"  # For compatibility
        
        # Ensure state directory exists
        self.state_dir.mkdir(exist_ok=True)
        
        # Browser instances
        self.playwright = None
        self.browser = None
        self.context = None
        self.selenium_driver = None
        
        # Session settings
        self.reuse_state = os.getenv('REUSE_STATE', 'true').lower() == 'true'
        self.force_per_job_relogin = os.getenv('FORCE_PER_JOB_RELOGIN', 'false').lower() == 'true'
        self.session_max_age = int(os.getenv('SESSION_MAX_AGE_SECONDS', '86400'))
    
    def check_proven_session(self) -> Dict[str, Any]:
        """
        Check if proven session file exists and is valid.
        
        Returns:
            Dict with session status information
        """
        if not self.proven_session_file.exists():
            return {
                "valid": False,
                "reason": "proven_session.json not found",
                "message": "Please run the proven login solution first"
            }
        
        try:
            with open(self.proven_session_file, 'r') as f:
                session_data = json.load(f)
            
            # Check required fields
            if 'method' not in session_data:
                return {
                    "valid": False,
                    "reason": "invalid_format",
                    "message": "Session file missing method field"
                }
            
            method = session_data['method']
            website_url = session_data.get('website_url', 'https://www.capcut.com')
            website_name = session_data.get('website_name', 'unknown')
            
            if method == 'undetected_chromedriver':
                if 'cookies' not in session_data or len(session_data['cookies']) == 0:
                    return {
                        "valid": False,
                        "reason": "no_cookies",
                        "message": "No cookies found in session file"
                    }
                
                # Check session age
                timestamp = session_data.get('timestamp', 0)
                age_seconds = time.time() - timestamp
                age_hours = age_seconds / 3600
                
                return {
                    "valid": True,
                    "method": method,
                    "website_url": website_url,
                    "website_name": website_name,
                    "cookies_count": len(session_data['cookies']),
                    "age_hours": round(age_hours, 1),
                    "user_agent": session_data.get('user_agent', 'Unknown'),
                    "last_url": session_data.get('last_url', 'Unknown')
                }
            
            else:
                # Playwright session
                if 'cookies' not in session_data and 'origins' not in session_data:
                    return {
                        "valid": False,
                        "reason": "no_session_data",
                        "message": "No session data found"
                    }
                
                return {
                    "valid": True,
                    "method": method,
                    "website_url": website_url,
                    "website_name": website_name,
                    "message": "Playwright session available"
                }
                
        except Exception as e:
            return {
                "valid": False,
                "reason": "read_error",
                "message": f"Error reading session file: {e}"
            }
    
    def create_context_with_proven_session(self, headless: bool = False) -> Optional[BrowserContext]:
        """
        Create browser context using existing proven session JSON file.
        SIMPLE: Just load the JSON and create context - no complex logic.
        
        Args:
            headless: Run browser in headless mode
            
        Returns:
            Browser context or None if failed
        """
        if not self.proven_session_file.exists():
            print(f"❌ Proven session file not found: {self.proven_session_file}")
            print("Please make sure proven_session.json exists in state/ directory")
            return None
        
        try:
            print("📂 Loading existing proven session...")
            
            # Load session data
            with open(self.proven_session_file, 'r') as f:
                session_data = json.load(f)
            
            print("✅ Proven session loaded successfully!")
            
            # Simple: Just create Playwright context with the session data
            return self._create_playwright_context_simple(session_data, headless)
                
        except Exception as e:
            print(f"❌ Failed to load proven session: {e}")
            return None
    
    def _create_playwright_context_simple(self, session_data: Dict[str, Any], headless: bool = False) -> Optional[BrowserContext]:
        """
        SIMPLE: Create Playwright context from proven session data.
        No complex logic - just load cookies and create context.
        """
        try:
            print("🚀 Creating Playwright context with proven session...")
            
            if not PLAYWRIGHT_AVAILABLE:
                print("❌ Playwright not available")
                return None
            
            # Start Playwright
            self.playwright = sync_playwright().start()
            
            # Launch browser
            self.browser = self.playwright.chromium.launch(
                headless=headless,
                args=[
                    '--no-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-blink-features=AutomationControlled'
                ]
            )
            
            # Determine target website and domain from session data
            website_url = session_data.get('website_url', 'https://www.capcut.com')
            parsed = urlparse(website_url)
            base_domain = parsed.netloc or 'www.capcut.com'
            default_cookie_domain = '.' + base_domain.lstrip('.')
            user_agent = session_data.get('user_agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

            # Create context
            self.context = self.browser.new_context(
                viewport={'width': 1280, 'height': 720},
                user_agent=user_agent
            )
            
            # Load cookies from session data
            if 'cookies' in session_data:
                print("🍪 Loading cookies from proven session...")
                
                # Go to target website first so domain is correct (works for any site)
                page = self.context.new_page()
                page.goto(website_url)
                time.sleep(2)
                
                # Add cookies
                cookies_added = 0
                for cookie in session_data['cookies']:
                    try:
                        # Convert to Playwright format
                        pw_cookie = {
                            'name': cookie['name'],
                            'value': cookie['value'],
                            'domain': cookie.get('domain', default_cookie_domain),
                            'path': cookie.get('path', '/'),
                            'httpOnly': cookie.get('httpOnly', False),
                            'secure': cookie.get('secure', False)
                        }
                        
                        if 'expiry' in cookie:
                            pw_cookie['expires'] = cookie['expiry']
                        
                        self.context.add_cookies([pw_cookie])
                        cookies_added += 1
                        
                    except Exception:
                        continue
                
                print(f"✅ Added {cookies_added} cookies")
                
                # Refresh to apply cookies
                page.reload()
                time.sleep(2)
                page.close()
            
            print("✅ Playwright context ready with proven session!")
            return self.context
            
        except Exception as e:
            print(f"❌ Failed to create Playwright context: {e}")
            return None

    def _create_context_from_selenium_session(self, session_data: Dict[str, Any], headless: bool = False) -> Optional[BrowserContext]:
        """Create Playwright context from Selenium session data."""
        try:
            print("🔄 Converting Selenium session to Playwright context...")
            
            if not PLAYWRIGHT_AVAILABLE:
                print("❌ Playwright not available")
                return None
            
            # Start Playwright
            self.playwright = sync_playwright().start()
            
            # Launch browser with similar settings to undetected chrome
            self.browser = self.playwright.chromium.launch(
                headless=headless,
                args=[
                    '--no-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-blink-features=AutomationControlled',
                    '--no-first-run',
                    '--disable-default-apps'
                ]
            )
            
            # Determine target website and domain
            website_url = session_data.get('website_url', 'https://www.capcut.com')
            parsed = urlparse(website_url)
            base_domain = parsed.netloc or 'www.capcut.com'
            default_cookie_domain = '.' + base_domain.lstrip('.')

            # Create context
            self.context = self.browser.new_context(
                viewport={'width': 1280, 'height': 720},
                user_agent=session_data.get('user_agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')
            )
            
            # Convert and add cookies
            print("🍪 Loading cookies from proven session...")
            page = self.context.new_page()
            
            # Go to target website first to set domain
            page.goto(website_url)
            time.sleep(2)
            
            # Add cookies from Selenium session
            cookies_added = 0
            for cookie in session_data.get('cookies', []):
                try:
                    # Convert Selenium cookie format to Playwright format
                    playwright_cookie = {
                        'name': cookie['name'],
                        'value': cookie['value'],
                        'domain': cookie.get('domain', default_cookie_domain),
                        'path': cookie.get('path', '/'),
                        'httpOnly': cookie.get('httpOnly', False),
                        'secure': cookie.get('secure', False)
                    }
                    
                    # Add expiry if present
                    if 'expiry' in cookie:
                        playwright_cookie['expires'] = cookie['expiry']
                    
                    self.context.add_cookies([playwright_cookie])
                    cookies_added += 1
                    
                except Exception as e:
                    # Some cookies might fail, continue with others
                    continue
            
            print(f"✅ Added {cookies_added} cookies to Playwright context")
            
            # Refresh page to apply cookies
            page.reload()
            time.sleep(2)
            
            # Test if session works
            print("🧪 Testing session validity...")
            test_urls = session_data.get('test_urls') or [website_url]
            test_target = test_urls[0]
            page.goto(test_target)
            time.sleep(3)
            
            if "login" not in page.url.lower():
                print("✅ Proven session successfully loaded into Playwright!")
                
                # Save as Playwright state for compatibility
                self._save_playwright_state()
                
                return self.context
            else:
                print("❌ Session appears to be expired")
                return None
                
        except Exception as e:
            print(f"❌ Failed to convert Selenium session: {e}")
            return None
    
    def _create_context_from_playwright_session(self, session_data: Dict[str, Any], headless: bool = False) -> Optional[BrowserContext]:
        """Create Playwright context from Playwright session data."""
        try:
            print("🔄 Loading Playwright session...")
            
            if not PLAYWRIGHT_AVAILABLE:
                print("❌ Playwright not available")
                return None
            
            # Start Playwright
            self.playwright = sync_playwright().start()
            
            # Launch browser
            self.browser = self.playwright.chromium.launch(
                headless=headless,
                args=['--no-sandbox', '--disable-dev-shm-usage'] if headless else []
            )
            
            # Create context with session data
            self.context = self.browser.new_context(
                storage_state=session_data,
                viewport={'width': 1280, 'height': 720},
                user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
            )
            
            print("✅ Playwright session loaded successfully!")
            return self.context
            
        except Exception as e:
            print(f"❌ Failed to load Playwright session: {e}")
            return None
    
    def _save_playwright_state(self):
        """Save current Playwright state for compatibility with main system."""
        try:
            if self.context:
                storage_state = self.context.storage_state()
                
                with open(self.state_file, 'w') as f:
                    json.dump(storage_state, f, indent=2)
                
                print(f"💾 Saved Playwright state to: {self.state_file}")
                
        except Exception as e:
            print(f"⚠️  Warning: Could not save Playwright state: {e}")
    
    def is_session_valid(self, context: BrowserContext) -> bool:
        """
        Check if the current session is valid by testing access to the saved website.
        
        Args:
            context: Browser context to test
            
        Returns:
            True if session is valid
        """
        try:
            print("🧪 Validating session...")
            
            # Load website_url and test_urls from proven_session.json
            website_url = "https://www.capcut.com"
            test_target = None
            try:
                if self.proven_session_file.exists():
                    with open(self.proven_session_file, 'r') as f:
                        session_data = json.load(f)
                    website_url = session_data.get('website_url', website_url)
                    test_urls = session_data.get('test_urls') or [website_url]
                    test_target = test_urls[0]
            except Exception:
                test_target = None

            if not test_target:
                test_target = website_url

            page = context.new_page()
            
            # Test access to target page (works for TikTok, YouTube, etc.)
            page.goto(test_target, timeout=30000)
            time.sleep(3)
            
            current_url = page.url.lower()
            
            if "login" not in current_url and "signin" not in current_url:
                print("✅ Session is valid!")
                page.close()
                return True
            else:
                print("❌ Session is invalid (redirected to login)")
                page.close()
                return False
                
        except Exception as e:
            print(f"❌ Session validation failed: {e}")
            return False
    
    def login_and_save(self, email: Optional[str] = None, password: Optional[str] = None, headful: bool = True) -> bool:
        """
        This method is kept for compatibility but redirects to proven solution.
        
        Returns:
            False with instructions to use proven solution
        """
        print("=" * 60)
        print("🚀 PROVEN LOGIN REQUIRED")
        print("=" * 60)
        print("This system now uses the proven login solution!")
        print()
        print("To login and create session:")
        print("1. Run: py FIXED_proven_solution.py")
        print("2. Choose option 1 (Undetected ChromeDriver Login)")
        print("3. Complete the login process")
        print("4. Run this automation again")
        print()
        print("The proven solution bypasses Google OAuth detection")
        print("and creates a session that works for months!")
        print("=" * 60)
        
        return False
    
    def create_selenium_driver_with_session(self) -> Optional[Any]:
        """
        Create Selenium driver with proven session (for advanced use cases).
        
        Returns:
            Selenium Chrome driver or None if failed
        """
        if not SELENIUM_AVAILABLE:
            print("❌ Selenium/undetected-chromedriver not available")
            return None
        
        session_status = self.check_proven_session()
        
        if not session_status["valid"] or session_status.get("method") != "undetected_chromedriver":
            print("❌ No valid undetected ChromeDriver session found")
            return None
        
        try:
            print("🚀 Creating Selenium driver with proven session...")
            
            # Load session data
            with open(self.proven_session_file, 'r') as f:
                session_data = json.load(f)

            website_url = session_data.get('website_url', 'https://www.capcut.com')
            
            # Create undetected Chrome driver
            options = uc.ChromeOptions()
            options.add_argument("--no-first-run")
            options.add_argument("--no-default-browser-check")
            
            self.selenium_driver = uc.Chrome(options=options)
            
            # Load cookies
            self.selenium_driver.get(website_url)
            time.sleep(2)
            
            for cookie in session_data.get('cookies', []):
                try:
                    self.selenium_driver.add_cookie(cookie)
                except:
                    continue
            
            # Refresh to apply cookies
            self.selenium_driver.refresh()
            time.sleep(3)
            
            print("✅ Selenium driver ready with proven session!")
            return self.selenium_driver
            
        except Exception as e:
            print(f"❌ Failed to create Selenium driver: {e}")
            return None
    
    def _cleanup(self):
        """Clean up browser instances."""
        try:
            if self.selenium_driver:
                self.selenium_driver.quit()
                self.selenium_driver = None
            
            if self.context:
                self.context.close()
                self.context = None
            
            if self.browser:
                self.browser.close()
                self.browser = None
            
            if self.playwright:
                self.playwright.stop()
                self.playwright = None
                
        except Exception as e:
            print(f"Warning: Cleanup error: {e}")
    
    def __del__(self):
        """Cleanup on destruction."""
        self._cleanup()


def main():
    """Test the proven browser manager."""
    print("=" * 60)
    print("🧪 TESTING PROVEN BROWSER MANAGER")
    print("=" * 60)
    
    browser = ProvenBrowser()
    
    # Check session status
    session_status = browser.check_proven_session()
    print(f"Session Status: {session_status}")
    
    if session_status["valid"]:
        print("\n🚀 Testing context creation...")
        context = browser.create_context_with_proven_session(headless=False)
        
        if context:
            print("✅ Context created successfully!")
            
            # Test session validity
            if browser.is_session_valid(context):
                print("✅ Session is working!")
            else:
                print("❌ Session validation failed")
            
            # Cleanup
            browser._cleanup()
        else:
            print("❌ Failed to create context")
    else:
        print("\n❌ No valid proven session found")
        print("Please run: py FIXED_proven_solution.py")


if __name__ == "__main__":
    main()
